### ISSUE TITLE
kindling-probe startup error: PERF_EVENT_IOC_SET_BPF

### ISSUE THREAD

**Issue by wangkun0817** [KindlingProject/kindling#242]
**Describe the bug**
kinding-probe startup error: kindling probe init err: PERF_EVENT_IOC_SET_BPF: File existsI20220608 02:52:43.553572 20962 env.cc:51] Shutting down

**How to reproduce?**
First encountered the "AAA" problem, and then solved it according to [FAQ](http://www.kindling.space:33215/project-3/doc-42/), and encountered this error after updating the mirror

**Screenshots**
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/25051370/172532052-f8474a09-f921-4351-b586-7c21fb33fc6d.png">

**What config did you use?**
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: kindling-agent
  name: kindling-agent
  namespace: kindling
spec:
  selector:
    matchLabels:
      k8s-app: kindling-agent
  template:
    metadata:
      labels:
        k8s-app: kindling-agent
    spec:
      serviceAccount: kindling-agent
      containers:
      - name: kindling-probe
        image: xxxxx/kubernetes/kindling-probe:latest-bymyself
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
              command:
                - sh
                - /pl/post_start.sh
        command:
        - /pl/docker-entrypoint.sh
        resources:
          limits:
            memory: 300Mi
          requests:
            memory: 300Mi
        env:
        - name: HOST_PROC
          value: /host/proc
        - name: PL_HOST_PATH
          value: /host
        - name: SYSDIG_HOST_ROOT
          value: /host
        - name: CLUSTER_ID
          value: CN0Z3
        securityContext:
          privileged: true
        readinessProbe:
          exec:
            command:
            - cat
            - /opt/kernel-support
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: shared-volume-kindling
          mountPath: /home/kindling
          readOnly: false
        - name: shared-volume-subpub
          mountPath: /home/kindling-sub
        - mountPath: /sys
          name: sys-vol
        - mountPath: /etc/modprobe.d
          name: modprobe-d
          readOnly: true
        - mountPath: /host/dev
          name: dev-vol
        - mountPath: /host/proc
          name: proc-vol
          readOnly: true
        - mountPath: /host/etc
          name: etc-vol
          readOnly: true
        - mountPath: /host/boot
          name: boot-vol
          readOnly: true
        - mountPath: /host/lib/modules
          name: modules-vol
          readOnly: true
        - mountPath: /host/usr
          name: usr-vol
          readOnly: true
        - mountPath: /host/run
          name: run-vol
        - mountPath: /host/var/run
          name: varrun-vol
        - mountPath: /dev/shm
          name: dshm
      - name: kindling-collector
        image: xxxxx/kubernetes/kindling-collector:v0.2.0
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            memory: 800Mi
          requests:
            memory: 300Mi
        env:
        - name: GOGC
          value: "400"
        - name: MY_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CLUSTER_ID
          value: CN0Z3
        volumeMounts:
        - mountPath: /etc/kindling/config
          name: kindlingcfg
        - name: shared-volume-kindling
          mountPath: /home/kindling
          readOnly: false
        - name: shared-volume-subpub
          mountPath: /home/kindling-sub
          readOnly: false
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostPID: true
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: kindlingcfg
        name: kindlingcfg
      - hostPath:
          path: /etc/modprobe.d
        name: modprobe-d
      - hostPath:
          path: /etc/os-release
          type: FileOrCreate
        name: osrel
      - emptyDir:
          medium: Memory
        name: dshm
      - hostPath:
          path: /dev
        name: dev-vol
      - hostPath:
          path: /proc
        name: proc-vol
      - hostPath:
          path: /etc
        name: etc-vol
      - hostPath:
          path: /boot
        name: boot-vol
      - hostPath:
          path: /lib/modules
        name: modules-vol
      - hostPath:
          path: /usr
        name: usr-vol
      - hostPath:
          path: /run
        name: run-vol
      - hostPath:
          path: /var/run
        name: varrun-vol
      - hostPath:
          path: /sys
        name: sys-vol
      - name: shared-volume-kindling
        emptyDir: {}
      - name: shared-volume-subpub
        emptyDir: {}
```

**Logs**
Please attach the logs by running the following command:
```
kubectl logs -f kindling-agent-xxx(replace with your podname) -n kindling -c kindling-probe
._kindling-falcolib-probe
kindling-falcolib-probe/
kindling-falcolib-probe/4.18.0-147.el8.x86_64.ko
kindling-falcolib-probe/3.10.0-862.el7.x86_64.ko
kindling-falcolib-probe/4.18.0-305.10.2.el8_4.x86_64.ko
kindling-falcolib-probe/4.19.91-21.2.al7.x86_64.o
kindling-falcolib-probe/4.18.0-147.el8.x86_64.o
kindling-falcolib-probe/3.10.0-1127.el7.x86_64.o
kindling-falcolib-probe/3.10.0-514.el7.x86_64.ko
kindling-falcolib-probe/4.19.91-21.2.al7.x86_64.ko
kindling-falcolib-probe/3.10.0-1160.el7.x86_64.o
kindling-falcolib-probe/5.10.23-5.al8.x86_64.o
kindling-falcolib-probe/3.10.0-1160.31.1.el7.x86_64.ko
kindling-falcolib-probe/3.10.0-1062.el7.x86_64.ko
kindling-falcolib-probe/4.18.0-80.el8.x86_64.ko
kindling-falcolib-probe/3.10.0-327.el7.x86_64.ko
kindling-falcolib-probe/4.19.67-16.al7.x86_64.o
kindling-falcolib-probe/4.19.34-11.al7.x86_64.ko
kindling-falcolib-probe/5.10.23-4.al8.x86_64.o
kindling-falcolib-probe/4.19.91-23.al7.x86_64.ko
kindling-falcolib-probe/4.18.0-240.el8.x86_64.o
kindling-falcolib-probe/4.19.91-22.2.al7.x86_64.o
kindling-falcolib-probe/5.10.23-5.al8.x86_64.ko
kindling-falcolib-probe/4.18.0-348.el8.x86_64.ko
kindling-falcolib-probe/4.18.0-193.el8.x86_64.ko
kindling-falcolib-probe/4.19.81-17.2.al7.x86_64.o
kindling-falcolib-probe/4.19.57-15.1.al7.x86_64.ko
kindling-falcolib-probe/4.19.91-19.1.al7.x86_64.o
kindling-falcolib-probe/4.19.91-21.al7.x86_64.o
kindling-falcolib-probe/5.10.60-9.al8.x86_64.ko
kindling-falcolib-probe/4.19.24-9.al7.x86_64.ko
kindling-falcolib-probe/5.10.23-6.al8.x86_64.ko
kindling-falcolib-probe/4.19.91-24.al7.x86_64.ko
kindling-falcolib-probe/4.19.91-25.6.al7.x86_64.ko
kindling-falcolib-probe/4.19.91-22.1.al7.x86_64.o
kindling-falcolib-probe/4.18.0-193.el8.x86_64.o
kindling-falcolib-probe/4.19.91-22.1.al7.x86_64.ko
kindling-falcolib-probe/3.10.0-693.el7.x86_64.ko
kindling-falcolib-probe/5.10.60-9.al8.x86_64.o
kindling-falcolib-probe/4.19.91-24.al7.x86_64.o
kindling-falcolib-probe/4.18.0-240.el8.x86_64.ko
kindling-falcolib-probe/4.19.91-25.6.al7.x86_64.o
kindling-falcolib-probe/4.19.91-23.al7.x86_64.o
kindling-falcolib-probe/4.19.91-25.1.al7.x86_64.o
kindling-falcolib-probe/4.19.91-21.al7.x86_64.ko
kindling-falcolib-probe/4.19.81-17.2.al7.x86_64.ko
kindling-falcolib-probe/4.19.91-18.al7.x86_64.ko
kindling-falcolib-probe/4.19.43-13.2.al7.x86_64.o
kindling-falcolib-probe/3.10.0-1160.el7.x86_64.ko
kindling-falcolib-probe/4.19.57-15.1.al7.x86_64.o
kindling-falcolib-probe/4.18.0-305.10.2.el8_4.x86_64.o
kindling-falcolib-probe/4.19.159.mizar.o
kindling-falcolib-probe/4.19.81-17.1.al7.x86_64.o
kindling-falcolib-probe/4.19.91-19.2.al7.x86_64.o
kindling-falcolib-probe/5.10.23-4.al8.x86_64.ko
kindling-falcolib-probe/4.19.81-17.1.al7.x86_64.ko
kindling-falcolib-probe/4.19.43-13.2.al7.x86_64.ko
kindling-falcolib-probe/4.19.91-24.1.al7.x86_64.o
kindling-falcolib-probe/4.18.0-80.el8.x86_64.o
kindling-falcolib-probe/4.19.91-22.2.al7.x86_64.ko
kindling-falcolib-probe/4.19.91-25.1.al7.x86_64.ko
kindling-falcolib-probe/4.19.91-23.1.al7.x86_64.o
kindling-falcolib-probe/4.18.0-305.3.1.el8.x86_64.o
kindling-falcolib-probe/3.10.0-1062.el7.x86_64.o
kindling-falcolib-probe/3.10.0-957.el7.x86_64.ko
kindling-falcolib-probe/4.19.67-16.al7.x86_64.ko
kindling-falcolib-probe/5.10.23-6.al8.x86_64.o
kindling-falcolib-probe/4.19.91-19.1.al7.x86_64.ko
kindling-falcolib-probe/4.19.91-24.1.al7.x86_64.ko
kindling-falcolib-probe/4.19.91-23.1.al7.x86_64.ko
kindling-falcolib-probe/4.18.0-348.el8.x86_64.o
kindling-falcolib-probe/4.18.0-305.3.1.el8.x86_64.ko
kindling-falcolib-probe/3.10.0-1160.31.1.el7.x86_64.o
kindling-falcolib-probe/4.19.91-19.2.al7.x86_64.ko
kindling-falcolib-probe/3.10.0-957.21.3.el7.x86_64.ko
kindling-falcolib-probe/4.19.91-18.al7.x86_64.o
kindling-falcolib-probe/3.10.0-1127.el7.x86_64.ko
* Mounting debugfs
* BPF probe located, it's now possible to start kindling
* Load probe succeeded, and will create /opt/kernel-support for kubernetes
I20220608 04:27:05.219300 22119 env.cc:47] Started: /pl/kindling_probe
I20220608 04:27:05.219357 22119 main.cpp:109] Start kindling probe...
I20220608 04:27:05.219368 22119 main.cpp:110] KINDLING_PROBE_VERSION: v0.1-2021-1221
kindling probe init err: PERF_EVENT_IOC_SET_BPF: File existsI20220608 04:27:06.429037 22119 env.cc:51] Shutting down
```
**Environment (please complete the following information)**
- Kindling agent version
    - v0.2.0
- Kindlinng-falcon-lib version
- Node OS version
    - CentOS Linux release 7.6.1810 (Core)
- Node Kernel version
    - kernel-ng-4.14.71-1.el7.centos.x86_64
    - kernel-ng-devel-4.14.71-1.el7.centos.x86_64
- Kubernetes version
    - v1.18.9
- Prometheus version
    - v2.20.0
    - kube-prometheus-0.6.0
- Grafana version
