### ISSUE TITLE
关于ebpf 获取ResponsePayload  requestPayload数据问题

### ISSUE THREAD

**Issue by xiaodaiit** [KindlingProject/kindling#473]
这边返回的数据都是截断过的，请问一下这个参数在哪控制的截取body大小

**Comment by dxsup** [comment]
有两个参数共同控制了最终输出数据中的body长度：
- 原始事件长度。默认是1000个字节，可以通过在容器启动的环境变量中更改：
```
        env:
        ...
        - name: SNAPLEN
          value: "1000"
```
- 保存的payload长度。在配置文件的`analyzers.networkanalyzer.protocol_config`会针对每种协议进行配置最终保存的payload长度。
https://github.com/KindlingProject/kindling/blob/5c2bf9530fbc6e941266e0e7a5feb6de8d125b66/deploy/agent/kindling-collector-config.yml#L81-L107

两个参数中，最终保存长度以较小的为准。
